/*$Id$
 *
 * This source file is a part of the Fresco Project.
 * Copyright (C) 2000 Stefan Seefeld <stefan@fresco.org> 
 * http://www.fresco.org
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Library General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Library General Public License for more details.
 *
 * You should have received a copy of the GNU Library General Public
 * License along with this library; if not, write to the
 * Free Software Foundation, Inc., 675 Mass Ave, Cambridge,
 * MA 02139, USA.
 */
#ifndef _Fresco_GGI_idl
#define _Fresco_GGI_idl

#include <Fresco/Controller.idl>
#include <Fresco/Kit.idl>

module GGI
{
  //. A interface to the GGI visual this Kit creates.
  interface Visual : Fresco::Controller
  {
    readonly attribute string name;
    readonly attribute string mode;
  };

  //. This Kit allows for direct access to the underlying GGI library. It
  //. returns a GGI visual. Of course this only works with the GGI console
  //. (which is the default at this time) enabled at compile time.
  //.
  //. This Kit can for example be used to run XGGI in a Berlin window.
  interface GGIKit : Fresco::Kit
  {
    //. Creates a GGI visual w pixels wide and h pixels high.
    Visual create_visual(in Fresco::PixelCoord w, in Fresco::PixelCoord h);
  };
};

#endif
