.TH VERSION "1" "August 2001" "version is 0.2.2" FSF
.SH NAME
version \- manual page for version is 0.2.2
.SH SYNOPSIS
.B Berlin
\fIa berlin display server\fR
.SH DESCRIPTION
.HP
\fB\-h\fR, \fB\-\-help\fR (help message)
.HP
\fB\-v\fR, \fB\-\-version\fR (version number)
.HP
\fB\-l\fR, \fB\-\-logger\fR [value] (switch logging on)
.HP
\fB\-t\fR, \fB\-\-tracer\fR (switch tracing on)
.HP
\fB\-p\fR, \fB\-\-profiler\fR (switch profiling on)
.HP
\fB\-d\fR, \fB\-\-drawing\fR <value> (the DrawingKit to choose)
.HP
\fB\-r\fR, \fB\-\-resource\fR <value> (the resource file to load (mandatory))
.HP
\fB\-e\fR, \fB\-\-execute\fR <value> (the command to execute upon startup)
