.TH berlin "1" "August 2001" "version is 0.3.0"
.SH NAME
berlin \- the berlin display server
.SH DESCRIPTION
.HP
\fB\-h\fR, \fB\-\-help\fR help message
.HP
\fB\-v\fR, \fB\-\-version\fR version number
.HP
\fB\-R\fR, \fB\-\-export-ref\fR means of exporting server reference
.HP
\fB\-l\fR, \fB\-\-logger\fR switch logging on
.HP
\fB\-t\fR, \fB\-\-tracer\fR switch tracing on
.HP
\fB\-p\fR, \fB\-\-profiler\fR switch profiling on
.HP
\fB\-d\fR, \fB\-\-drawing\fR the DrawingKit to choose
.HP
\fB\-r\fR, \fB\-\-resource\fR the resource file to load
.HP
\fB\-e\fR, \fB\-\-execute\fR the command to execute upon startup
.HP
\fB\-c\fR, \fB\-\-console\fR the console to choose
