#!/bin/sh

set -e

trap "echo ;\
      echo 'Received signal.  Aborting removal of Berlin package.' ;\
      echo ;\
      exit 1" 1 2 3 15

case "$1" in
  remove) ;;
  purge) ;;
  upgrade|failed-upgrade|abort-install|abort-upgrade|disappear) exit 0 ;;
  *) 
    echo "ERROR: Berlin postrm called with unknown argument \"$1\"."
    echo "Aborting removal of Berlin package."
    exit 1 ;;
esac

if grep -qs ^/usr/X11R6/lib\$ /etc/ld.so.conf; then
  TMPFILE=/tmp/ld.so.conf.$$
  sed '/^\/usr\/Berlin\/lib$/d' /etc/ld.so.conf > $TMPFILE
  mv $TMPFILE /etc/ld.so.conf
fi

ldconfig

exit
