.TH Warsaw 1 "19 August 2001"
.SH NAME
Warsaw-config - script to get information about the installed version of Babylon
.SH SYNOPSIS
.B Warsaw-config
[\-\-prefix\fI[=DIR]\fP] [\-\-exec\-prefix\fI[=DIR]\fP] [\-\-version] [\-\-cppflags] [\-\-cxxflags] [\-\-libs]
.SH DESCRIPTION
.PP
\fIWarsaw-config\fP is a tool that is used to configure to determine
the compiler and linker flags that should be used to compile
and link programs that use \fIWarsaw\fP. It is also used internally
to the .m4 macros for GNU autoconf that are included with \fIBerlin\fP.
.
.SH OPTIONS
.l
\fIWarsaw-config\fP accepts the following options:
.TP 8
.B  \-\-version
Print the currently installed version of \fIWarsaw\fP on the standard output.
.TP 8
.B  \-\-libs
Print the linker flags that are necessary to link a \fIWarsaw\fP program.
.TP 8
.B  \-\-cflags
Print the compiler flags that are necessary to compile a \fIWarsaw\fP program.
.TP 8
.B  \-\-prefix=PREFIX
If specified, use PREFIX instead of the installation prefix that \fIWarsaw\fP
was built with when computing the output for the \-\-cppflags, \-\-cxxflags and
\-\-libs options. This option is also used for the exec prefix
if \-\-exec\-prefix was not specified. This option must be specified
before any \-\-cppflags, \-\-cxxflags or \-\-libs options.
.TP 8
.B  \-\-exec\-prefix=PREFIX
If specified, use PREFIX instead of the installation exec prefix that \fIWarsaw\fP
was built with when computing the output for the \-\-cppflags, \-\-cxxflags and
\-\-libs options. This option must be specified
before any \-\-cppflags, \-\-cxxflags or \-\-libs options.
.SH COPYRIGHT
Copyright \(co  2001 Bastian Blank

Permission to use, copy, modify, and distribute this software and its
documentation for any purpose and without fee is hereby granted,
provided that the above copyright notice appear in all copies and that
both that copyright notice and this permission notice appear in
supporting documentation.
