/*$Id$
 *
 * This source file is a part of the Fresco Project.
 * Copyright (C) 1998 Graydon Hoare <graydon@fresco.com> 
 * Copyright (C) 1999, 2000 Stefan Seefeld <stefan@fresco.org> 
 * http://www.fresco.org
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Library General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Library General Public License for more details.
 *
 * You should have received a copy of the GNU Library General Public
 * License along with this library; if not, write to the
 * Free Software Foundation, Inc., 675 Mass Ave, Cambridge,
 * MA 02139, USA.
 */
#ifndef _Fresco_Command_idl
#define _Fresco_Command_idl

#pragma prefix "fresco.org"

module Fresco
{
  //. Commands are anonymous encapsulated actions. 
  interface Command
    {
      //. The action performed by this Command. The passed parameter contains
      //. additional information this Command might need.
      void execute(in any a);
      //. Destroy this Command.
      void destroy();
    };
  
  //. A composite Command. You can add other Commands to this and those
  //. will get executed in that order whenever the MacroCommand gets executed.
  interface MacroCommand : Command
    {
      //. Add a Command to the end of the list of Commands of this
      //. MacroCommand.
      void append(in Command c);
      //. Add a Command to the begining of the list of Commands of this
      //. MacroCommand.
      void prepend(in Command c);
    };
};

#endif
