// MenuKit
// Note that MenuKit will be integrated into WidgetKit once the prototype
// stage is complete.

#ifndef _Warsaw_MenuKit_idl
#define _Warsaw_MenuKit_idl

#include <Warsaw/Controller.idl>
#include <Warsaw/Command.idl>

module Warsaw {

    //. Menu kit that implements menubar and popup menus.
    //. FIXME: Add more documentation when this gets integrated into the
    //.        WidgetKit!
    interface MenuKit {
	//. Create a new horizontal menu bar
	Controller menu_bar();
	//. Create a new popup menu. This may be stand-alone or the submenu
	//. for a MenuItem
	Controller menu_popup();
	//. Create a menu item with the given label and callback. The menu
	//. argument is the top-level menu, and is used to test the 'running'
	//. state
	Controller menu_item(in Controller menu, in Graphic label, in Warsaw::Axis axis, in Command callback);
	//. Create a menu item with a sub menu
	Controller submenu_item(in Controller menu, in Graphic label, in Warsaw::Axis axis, in Controller submenu);
    };
};

#endif
