/*$Id$
 *
 * This source file is a part of the Fresco Project.
 * Copyright (C) 1999 Brent Fulgham <bfulgham@debian.org>
 * Copyright (C) 1999, 2000 Stefan Seefeld <stefan@fresco.org>
 * http://www.fresco.org
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Library General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Library General Public License for more details.
 *
 * You should have received a copy of the GNU Library General Public
 * License along with this library; if not, write to the
 * Free Software Foundation, Inc., 675 Mass Ave, Cambridge,
 * MA 02139, USA.
 */

#ifndef _Fresco_RasterKit_idl
#define _Fresco_RasterKit_idl

#include <Fresco/Types.idl>
#include <Fresco/Kit.idl>
#include <Fresco/Raster.idl>

#pragma prefix "fresco.org"

module Fresco
{
  //. The RasterKit is used to add pixelbased Images into the SceneGraph.

  //. Raster holds the detailed image data corresponding to a picture
  //. or texture mapping on the screen (or in memory).
  //.
  //. It is generally contained within an Image object, which handles
  //. all of the nasty details related to layout and so forth.
  interface RasterKit : Kit
    {
      //. Create an empty Raster.
      Raster create_empty_raster();
      //. Create a Raster from a file. 'rasterpath' from Berlin's config file
      //. is prepended! If the file is not found a the ImageKit
      //. falls back to 'berlin-128.png' in 'rasterpath'.
      // FIXME: This should throw an exception if the file is not found.
      //        The current behaviour is not useful for real-world
      //        applications.
      Raster create_raster(in string file) raises (CreationFailureException);
    };
};

#endif
