/*$Id$
 *
 * This source file is a part of the Fresco Project.
 * Copyright (C) 1999, 2000 Stefan Seefeld <stefan@fresco.org> 
 * Copyright (C) 1999 Graydon Hoare <graydon@fresco.org> 
 * http://www.fresco.org
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Library General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Library General Public License for more details.
 *
 * You should have received a copy of the GNU Library General Public
 * License along with this library; if not, write to the
 * Free Software Foundation, Inc., 675 Mass Ave, Cambridge,
 * MA 02139, USA.
 */
#ifndef _Fresco_State_idl
#define _Fresco_State_idl

#include <Fresco/Graphic.idl>
#include <Fresco/DrawingKit.idl>

#pragma prefix "fresco.org"

module Fresco
{
  interface Transform;
  interface Region;
  interface Raster;

  // FIXME: What is this?
  interface DrawingState : Graphic
    {
//       attribute Transform transformation;
//       attribute Region clipping;
      attribute Color foreground;
      attribute Color lighting;
      attribute Coord point_size;
      attribute Coord line_width;
      attribute DrawingKit::Endstyle line_endstyle;
      attribute DrawingKit::Fillstyle surface_fillstyle;
      attribute Raster texture;
    };

  // FIXME: What is this?
  interface FontState : Graphic
    {
      attribute unsigned long font_size;
      attribute unsigned long font_weight;
      attribute Unistring font_family;
      attribute Unistring font_subfamily;
      attribute Unistring font_fullname;
      attribute Unistring font_style;
    };
};

#endif
