/*$Id$
 *
 * This source file is a part of the Fresco Project.
 * Copyright (C) 1999 Stefan Seefeld <stefan@fresco.org> 
 * http://www.fresco.org
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Library General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Library General Public License for more details.
 *
 * You should have received a copy of the GNU Library General Public
 * License along with this library; if not, write to the
 * Free Software Foundation, Inc., 675 Mass Ave, Cambridge,
 * MA 02139, USA.
 */
#ifndef _Fresco_Subject_idl
#define _Fresco_Subject_idl

#include <Fresco/Types.idl>
#include <Fresco/RefCountBase.idl>
#include <Fresco/Identifiable.idl>

#pragma prefix "fresco.org"

module Fresco
{
  interface Observer;

  //. Subject defines what it means to be observable.
  //. Observers can be bound to it so calling notify
  //. will call them back
  interface Subject : RefCountBase, Identifiable
    {
      //. Add an observer to this object. All observers will be
      //. notified after any change to the state of an Object.
      void attach(in Observer o);
      //. Remove an object from the list of observers.
      void detach(in Observer o);
      //. Notify all observers of the change. The argument may
      //. contain some subject-specific detail for a given change.
      void notify(in any a);
      //. Block / unblock the notification of the observers.
      void block(in boolean b);  
    };
};

#endif
