/*$Id$
 *
 * This source file is a part of the Berlin Project.
 * Copyright (C) 1999 Stefan Seefeld <stefan@berlin-consortium.org> 
 * http://www.berlin-consortium.org
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Library General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Library General Public License for more details.
 *
 * You should have received a copy of the GNU Library General Public
 * License along with this library; if not, write to the
 * Free Software Foundation, Inc., 675 Mass Ave, Cambridge,
 * MA 02139, USA.
 */
#ifndef _Telltale_idl
#define _Telltale_idl

#include <Warsaw/Subject.idl>

interface TelltaleConstraint;

interface Telltale : Subject
{
  typedef unsigned long Mask;
  attribute TelltaleConstraint constraint;
  void set(in Mask m);
  void clear(in Mask m);
  boolean test(in Mask m);
  void modify(in Mask m, in boolean b);
};

interface TelltaleConstraint
{
  void add(in Telltale t);
  void remove(in Telltale t);
  void trymodify(in Telltale t, in Telltale::Mask m, in boolean b);
};

#endif /* _Telltale_idl */
