#ifndef _TextKit_idl
#define _TextKit_idl

//
// $Id$
//
// This source file is a part of the Berlin Project.
// Copyright (C) 1998 Graydon Hoare <graydon@pobox.com> 
// http://www.berlin-consortium.org
//
// This program is free software; you can redistribute it and/or
// modify it under the terms of the GNU Library General Public License
// as published by the Free Software Foundation; either version 2 of
// the License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful, but
// WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
// General Public License for more details.
//
// You should have received a copy of the GNU Library General Public
// License along with this program; if not, write to the Free Software
// Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
//
//

#include "Cloneable.idl"
#include "Graphic.idl"
#include "Types.idl"

// TextKit produces text chunks (flyweights) as well as decorators which set the
// current font state as a traversal passes through them.

interface TextBuffer;

interface TextKit : Cloneable {
    
  Graphic chunk(in Unistring u);    
  Graphic simpleViewer(in TextBuffer buf);

  Graphic size(in Graphic body, in unsigned long ems);
  Graphic weight(in Graphic body, in unsigned long wt);
  Graphic family(in Graphic body, in Unistring fam);
  Graphic subFamily(in Graphic body, in Unistring fam);
  Graphic fullName(in Graphic body, in Unistring name);
  Graphic style(in Graphic body, in Unistring sty);
  Graphic fontAttr(in Graphic body, in NVPair nvp);

};

#endif
