#!/usr/bin/env python

import sys
import string

import Warsaw


def main():
	# Create a shorter reference to the App module, and initialise it
	a = Warsaw.App
	a.init()

	# Create a pixmap
	pixmap = a.pixmap("etc/PNG/berlin-128.png")

	# Create a grid, and place two pixmaps in it
	grid = a.layout.fixedGrid(Warsaw.Grid.Index(2,1))
	grid.replace(a.layout.valign(pixmap, 1.0), Warsaw.Grid.Index(0, 0))
	grid.replace(a.layout.valign(pixmap, 0.5), Warsaw.Grid.Index(1, 0))

	# Create a text buffer and a viewer
	buffer = a.command.text()
	buffer.insertString(a.toUni("Welcome to Berlin!"))
	textview = a.text.simpleViewer(buffer)

	# Create a vertical box of the grid and the text
	vbox = a.layout.vbox()
	vbox.append(grid)
	vbox.append(a.layout.margin(textview,40.0))

	# Group and shell the grid
	glyph = a.text.chunk(a.toUni("Label"))
	label = a.layout.margin(glyph, 20.)
	choice = a.widget.toggleChoice()
	choice.appendItem(a.tool.rgb(label, 0., 0., 0.))
	#	button = a.widget.button(a.tool.rgb(label, 0., 0., 0.), a.command._nil)
	frame = Warsaw.ToolKit.FrameSpec(Warsaw.ToolKit.none, 0.5)
	group = a.tool.group(a.tool.frame(choice, 20., frame, 1))
	shell = a.desktop.shell(group)

	a.loop()

if __name__ == '__main__':
	main()
