#!/usr/bin/env python

import sys, time
import string

# Import Fresco client lib
import Fresco
import FrescoClient

class DemoApp (FrescoClient.App):
    def run(self):
	# Create a pixmap
	pixmap = kits.figures.pixmap(kits.rasters.create_raster("fresco.png"))
	margin = kits.layout.margin_flexible(pixmap, 100., 500., 100.)
	spec = Fresco.ToolKit.FrameSpec(Fresco.ToolKit.outset, 0.5)
        demo = kits.tools.frame(margin, 10., spec, 1)
	group = kits.tools.group(kits.tools.debugger(demo, "debug"))
    	shell = kits.desktop.shell(group, connection.clientContext)



def main():
    # Create singletons
    global app, kits, connection
    connection = FrescoClient.get_connection()
    kits = FrescoClient.get_kits()
    app = DemoApp()

    app.run()

    # Wait for the quit event
    app.quit.wait()

    # Tell the orb to shutdown (and wait for pending calls to complete)
    connection.orb.shutdown(1)

if __name__ == '__main__':
    main()

# vim: ts=8:sts=4:sw=4
