#!/usr/bin/env python

import sys
import string

# Import the CORBA module
from omniORB import CORBA

# Import the Warsaw stubs
import Warsaw
import POA_Warsaw
import CosNaming
# Define an implementation of the ClientContext interface
class ClientContextImpl (POA_Warsaw.ClientContext):
    def userName(self): return "joe"
    def ping(self): return

def main():
    # Initialise the ORB
    orb = CORBA.ORB_init(sys.argv, CORBA.ORB_ID)
    # Find the POA
    poa = orb.resolve_initial_references("RootPOA")
    # Activate the POA
    poaManager = poa._get_the_POAManager()
    poaManager.activate()
    # Create an ClientContext
    ci = ClientContextImpl()
    # Create an object reference, and implicitly activate the object
    client = ci._this()

    # get a server context
    context = orb.resolve_initial_references("NameService")
    name = [CosNaming.NameComponent("IDL:Server:1.0", "Object")]
    server = context.resolve(name)
    context  = server.newServerContext(client)

    # get some kits
    properties = []
    object  = context.resolve("IDL:DesktopKit:1.0", properties)
    desktop = object._narrow(Warsaw.DesktopKit)
    object  = context.resolve("IDL:ToolKit:1.0", properties)
    tool    = object._narrow(Warsaw.ToolKit)
    object  = context.resolve("IDL:CommandKit:1.0", properties)
    command = object._narrow(Warsaw.CommandKit)
    object  = context.resolve("IDL:LayoutKit:1.0", properties)
    layout  = object._narrow(Warsaw.LayoutKit)
    object  = context.resolve("IDL:WidgetKit:1.0", properties)
    widget  = object._narrow(Warsaw.WidgetKit)
    object  = context.resolve("IDL:FigureKit:1.0", properties)
    figure  = object._narrow(Warsaw.FigureKit)
    object  = context.resolve("IDL:ImageKit:1.0", properties)
    image   = object._narrow(Warsaw.ImageKit)
    object  = context.resolve("IDL:GadgetKit:1.0", properties)
    gadget  = object._narrow(Warsaw.GadgetKit)

    pixmap = figure.pixmap(image.create("../etc/PNG/png.png"))
    hbox   = layout.hbox();
    hbox.append(widget.button(pixmap, Warsaw.Command._nil))
    hbox.append(widget.button(pixmap, Warsaw.Command._nil))
    hbox.append(widget.button(pixmap, Warsaw.Command._nil))
    adjustable = command.bvalue(0., 360., 360., 10., 10.)
    vbox = layout.vbox()
    vbox.append(widget.slider(adjustable, Warsaw.xaxis))
    vbox.append(tool.debugger(gadget.transformer(tool.debugger(hbox, "inner"), adjustable), "outer"))
    shell = desktop.shell(tool.group(vbox))
    while 1:
	line = sys.stdin.readline()
	if len(line) == 1: break

if __name__ == '__main__':
    main()
