#!/usr/bin/env python

import sys, time
import string

# Import the CORBA module
from omniORB import CORBA
import CosNaming

# Import the Fresco stubs
import Fresco, Unidraw

class DemoApp (Fresco.App):
    def run(self):
	# FIXME: This is bitrotted
	editor = kits.unidraw.create_editor()
	view   = editor.create_viewer(3000, 3000)
	shell  = kits.desktop.shell(view, connection.clientContext)

def main():
    # Create singletons
    global app, kits, connection
    connection = Fresco.get_connection()
    kits = Fresco.get_kits()
    app = DemoApp()

    app.run()

    # Wait for the quit event
    app.quit.wait()

    # Tell the orb to shutdown (and wait for pending calls to complete)
    connection.orb.shutdown(1)

if __name__ == '__main__':
    main()
